<?php

namespace App\Filament\Pages;

use App\Models\Setting;
use BackedEnum;
use UnitEnum;
use Filament\Actions\Action;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Schema;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Support\Icons\Heroicon;

class ReportSettings extends Page implements HasForms
{
    use InteractsWithForms;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedCog6Tooth;
    protected static string|UnitEnum|null $navigationGroup = 'Reports';
    protected static ?int $navigationSort = 0;
    protected static ?string $navigationLabel = 'Report Settings (Header/Footer, Mail)';
    protected static ?string $title = 'Report Settings — Header/Footer & Mail Formats';

    protected string $view = 'filament.pages.report-settings';

    public ?array $data = [];

    public function mount(): void
    {
        $companyName = Setting::get('company.name', config('app.name', 'Travel Company'));
        $this->data = [
            'report_header_title' => Setting::get('reports.header_title', $companyName . ' — Travel Reports'),
            'report_header_subtitle' => Setting::get('reports.header_subtitle', Setting::get('company.address', 'Kathmandu, Nepal') . ' | ' . Setting::get('company.email', 'info@example.com') . ' | ' . Setting::get('company.phone', '+977-9800000000')),
            'report_header_logo' => Setting::get('reports.header_logo', Setting::get('company.logo', '')),
            'report_footer_text' => Setting::get('reports.footer_text', 'Generated by ' . $companyName . ' — Confidential — © ' . date('Y') . ' ' . $companyName),
            'report_footer_show_page_number' => Setting::get('reports.footer_show_page_number', '1'),
            'report_company_address' => Setting::get('reports.company_address', Setting::get('company.address', 'Kathmandu, Nepal')),
            'report_primary_color' => Setting::get('reports.primary_color', Setting::get('company.primary_color', '#f59e0b')),
            'mail_booking_subject' => Setting::get('mail.booking_subject', 'Your Booking Confirmation — {{booking_code}}'),
            'mail_booking_body' => Setting::get('mail.booking_body', '<p>Dear {{customer_name}},</p><p>Your booking {{booking_code}} for {{package_title}} is confirmed.</p>'),
            'mail_inquiry_subject' => Setting::get('mail.inquiry_subject', 'Thank you for your inquiry'),
            'mail_inquiry_body' => Setting::get('mail.inquiry_body', '<p>Dear {{name}},</p><p>We received your inquiry.</p>'),
            'mail_bulk_subject' => Setting::get('mail.bulk_subject', 'Greetings from {{company_name}}'),
            'mail_bulk_body' => Setting::get('mail.bulk_body', '<p>Dear {{name}},</p><p>Check our latest packages!</p>'),
            'mail_from_name' => Setting::get('mail.from_name', $companyName),
            'mail_from_email' => Setting::get('mail.from_email', Setting::get('company.email', 'info@example.com')),
        ];
        $this->form->fill($this->data);
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->statePath('data')
            ->components([
                Tabs::make('Report Settings Tabs')
                    ->columnSpanFull()
                    ->tabs([
                        Tab::make('Report Header/Footer')
                            ->icon('heroicon-o-document-text')
                            ->schema([
                                Section::make('Tab Information')
                                    ->icon('heroicon-o-information-circle')
                                    ->collapsible()
                                    ->schema([
                                        \Filament\Forms\Components\Placeholder::make('report_header_tab_info')
                                            ->content('This tab manages related data.')
                                            ->columnSpanFull(),
                                    ])
                                    ->columnSpanFull(),
                                Section::make('Report Header')
                                    ->description('Header on every PDF')
                                    ->columns(2)
                                    ->columnSpanFull()
                                    ->schema([
                                        TextInput::make('report_header_title')
                                            ->label('Header Title')
                                            ->placeholder('Company travel reports')
                                            ->maxLength(255)
                                            ->helperText('Company travel reports'),
                                        TextInput::make('report_primary_color')
                                            ->label('Primary Color')
                                            ->placeholder('#f59e0b')
                                            ->helperText('Header background'),
                                        TextInput::make('report_header_subtitle')
                                            ->label('Header Subtitle')
                                            ->helperText('Address | Email | Phone')
                                            ->columnSpanFull(),
                                        FileUpload::make('report_header_logo')
                                            ->label('Header Logo')
                                            ->image()
                                            ->directory('reports/header')->disk('public')->visibility('public')
                                            ->helperText('200x60 PNG')
                                            ->columnSpanFull()
                                            ->maxSize(5120)
                                            ->acceptedFileTypes(['image/jpeg','image/jpg','image/png','image/webp'])
                                            ->imagePreviewHeight('250')->openable()->downloadable(),
                                    ]),
                                Section::make('Report Footer')
                                    ->description('Footer on every PDF')
                                    ->columns(2)
                                    ->columnSpanFull()
                                    ->schema([
                                        Textarea::make('report_footer_text')
                                            ->label('Footer Text')
                                            ->rows(2)
                                            ->helperText('Confidential footer')
                                            ->columnSpanFull(),
                                        TextInput::make('report_company_address')
                                            ->label('Company Address')
                                            ->columnSpanFull(),
                                        \Filament\Forms\Components\Toggle::make('report_footer_show_page_number')
                                            ->label('Show Page Number')
                                            ->helperText('Add Page 1 of N')
                                            ->inline(false),
                                    ]),
                            ]),

                        Tab::make('Mail Templates')
                            ->icon('heroicon-o-envelope')
                            ->schema([
                                Section::make('Tab Information')
                                    ->icon('heroicon-o-information-circle')
                                    ->collapsible()
                                    ->schema([
                                        \Filament\Forms\Components\Placeholder::make('mail_templates_tab_info')
                                            ->content('This tab manages related data.')
                                            ->columnSpanFull(),
                                    ])
                                    ->columnSpanFull(),
                                Section::make('Booking Mail')
                                    ->description('Sent on booking create')
                                    ->columnSpanFull()
                                    ->schema([
                                        TextInput::make('mail_booking_subject')
                                            ->label('Booking Subject')
                                            ->helperText('Use {{booking_code}}')
                                            ->columnSpanFull(),
                                        RichEditor::make('mail_booking_body')
                                            ->label('Booking Body')
                                            ->helperText('Use {{customer_name}} etc')
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Inquiry Mail')
                                    ->columnSpanFull()
                                    ->schema([
                                        TextInput::make('mail_inquiry_subject')
                                            ->label('Inquiry Subject')
                                            ->helperText('Use {{name}}')
                                            ->columnSpanFull(),
                                        RichEditor::make('mail_inquiry_body')
                                            ->label('Inquiry Body')
                                            ->helperText('Use {{name}}, {{email}}')
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Bulk Mail Template')
                                    ->description('For bulk mail customers')
                                    ->columnSpanFull()
                                    ->schema([
                                        TextInput::make('mail_bulk_subject')
                                            ->label('Bulk Mail Subject')
                                            ->helperText('Use {{name}}')
                                            ->columnSpanFull(),
                                        RichEditor::make('mail_bulk_body')
                                            ->label('Bulk Mail Body')
                                            ->helperText('Use {{name}}, {{email}}')
                                            ->columnSpanFull(),
                                        TextInput::make('mail_from_name')
                                            ->label('From Name')
                                            ->helperText('Sender name'),
                                        TextInput::make('mail_from_email')
                                            ->label('From Email')
                                            ->email()
                                            ->helperText('Sender email'),
                                    ]),
                            ]),
                    ])            ])
            ->columns(1);
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('save')
                ->label('Save Report Settings')
                ->color('primary')
                ->action('save'),
        ];
    }

    public function save(): void
    {
        $raw = $this->form->getState();
        $data = $raw;
        if (isset($raw['data']) && is_array($raw['data']) && !array_key_exists('report_header_title', $raw)) {
            $data = $raw['data'];
        }
        if (empty($data) && !empty($this->data)) {
            $data = array_merge($this->data, $data);
        }
        \Illuminate\Support\Facades\Log::info('ReportSettings save', ['raw' => $raw, 'resolved' => $data]);
        $map = [
            'report_header_title' => ['key' => 'reports.header_title', 'group' => 'reports'],
            'report_header_subtitle' => ['key' => 'reports.header_subtitle', 'group' => 'reports'],
            'report_header_logo' => ['key' => 'reports.header_logo', 'group' => 'reports'],
            'report_footer_text' => ['key' => 'reports.footer_text', 'group' => 'reports'],
            'report_footer_show_page_number' => ['key' => 'reports.footer_show_page_number', 'group' => 'reports'],
            'report_company_address' => ['key' => 'reports.company_address', 'group' => 'reports'],
            'report_primary_color' => ['key' => 'reports.primary_color', 'group' => 'reports'],
            'mail_booking_subject' => ['key' => 'mail.booking_subject', 'group' => 'mail'],
            'mail_booking_body' => ['key' => 'mail.booking_body', 'group' => 'mail'],
            'mail_inquiry_subject' => ['key' => 'mail.inquiry_subject', 'group' => 'mail'],
            'mail_inquiry_body' => ['key' => 'mail.inquiry_body', 'group' => 'mail'],
            'mail_bulk_subject' => ['key' => 'mail.bulk_subject', 'group' => 'mail'],
            'mail_bulk_body' => ['key' => 'mail.bulk_body', 'group' => 'mail'],
            'mail_from_name' => ['key' => 'mail.from_name', 'group' => 'mail'],
            'mail_from_email' => ['key' => 'mail.from_email', 'group' => 'mail'],
        ];
        foreach ($map as $field => $meta) {
            if (array_key_exists($field, $data)) {
                $val = $data[$field];
                if (is_array($val)) $val = json_encode($val);
                Setting::set($meta['key'], $val, $meta['group'], false);
            }
        }
        foreach (['reports','mail'] as $g) {
            \Illuminate\Support\Facades\Cache::forget('settings:'.$g);
        }
        \Illuminate\Support\Facades\Cache::forget('settings:reports+mail');
        // Refresh form state
        $saved = \App\Models\Setting::whereIn('key', array_column($map, 'key'))->pluck('value', 'key')->toArray();
        $this->data = array_merge($this->data, $data);
        foreach ($saved as $k => $v) {
            $field = array_search($k, array_column($map, 'key'));
            // Keep $this->data synced
        }
        $this->form->fill($this->data);
        \Illuminate\Support\Facades\Log::info('ReportSettings after save', $saved);
        Notification::make()->title('Report settings saved')->success()->send();
    }
}
